### ISSUE TITLE
Databáze razítek nezobrazuje scany razítek

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/razitka#1]
Dobré odpoledne,
v databázi razítek http://195.113.132.51:8080/razitka/#list/View:Exemplar se nezobrazují obrázky. Objevuje se znak prázdný, přestože by tam měl obrázek být - viz print screen. Můžete prosím zjistit, kde je problém? Děkuji. 
TF
![razitka](https://user-images.githubusercontent.com/16835471/42094233-62ddca94-7baf-11e8-9eda-6a30604e4baa.jpg)

**Comment by vlahoda** [comment]
zaviram, uz neni aktualni
